--SELECT * FROM public.languages;
--select organisation.number_of_members, organisation.organisation_name from organisation inner join languages
--on organisation.organisation_name = languages.organisation_name
--select language_typ, number_of_bytes from public.languages where organisation_name = 'facebook' order by number_of_bytes desc
--select sum(number_of_bytes) from public.languages where organisation_name = 'facebook'
--select organisation_name, number_of_members, number_of_repositories, number_of_languages from organisation where organisation_name= 'facebook'
--select organisation_name, number_of_bytes from public.languages where language_typ= 'Python'